"""DocumentChunk — parsed text segments for search + RAG.

One KnowledgeItem → N DocumentChunks. A chunk is the unit of both
Elasticsearch indexing (#16) and Qdrant vectorization (#22). Keeping them
in Postgres as source-of-truth means ES/Qdrant can be rebuilt from scratch.

Issue #43 adds chunk versioning: ``version``, ``is_current``,
``content_hash``, ``doc_version``. Old chunks are kept with
``is_current=False`` for audit; only current chunks are indexed in
ES/Qdrant.
"""

from datetime import datetime
from enum import Enum as PyEnum

from sqlalchemy import JSON, Boolean, DateTime, Enum, ForeignKey, Integer, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.core.database import Base


class ParseStatus(str, PyEnum):
    PENDING = "pending"
    PARSING = "parsing"
    PARSED = "parsed"
    FAILED = "failed"


class DocumentChunk(Base):
    __tablename__ = "document_chunks"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    knowledge_item_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("knowledge_items.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    # Ordinal position within the document. Lets us re-assemble or cite
    # "paragraph 3" in answers.
    chunk_index: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    content: Mapped[str] = mapped_column(Text, nullable=False)
    token_count: Mapped[int] = mapped_column(Integer, default=0, nullable=False)
    # Qdrant point ID — nullable until #22 embeds it.
    vector_id: Mapped[str | None] = mapped_column(String(100), nullable=True)

    # Chunk versioning (Issue #43).
    content_hash: Mapped[str | None] = mapped_column(String(16), nullable=True, index=True)
    version: Mapped[int] = mapped_column(Integer, default=1, server_default="1", nullable=False)
    is_current: Mapped[bool] = mapped_column(
        Boolean, default=True, server_default="true", nullable=False, index=True
    )
    doc_version: Mapped[int] = mapped_column(Integer, default=1, server_default="1", nullable=False)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    knowledge_item: Mapped["KnowledgeItem"] = relationship(
        "KnowledgeItem",
        backref="chunks",
    )

    def __repr__(self) -> str:
        return f"<DocumentChunk doc={self.knowledge_item_id} idx={self.chunk_index}>"


class KCard(Base):
    """Knowledge Card — chunk-level structured summary (Issue #43).

    Generated by LLM for each current chunk. Old K-Cards are preserved
    when their chunk is superseded (is_current=False).
    """

    __tablename__ = "kcards"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, index=True)
    chunk_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("document_chunks.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    title: Mapped[str] = mapped_column(String(500), nullable=False)
    summary: Mapped[str] = mapped_column(Text, nullable=False)
    tags: Mapped[list] = mapped_column(JSON, default=list, nullable=False)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    chunk: Mapped["DocumentChunk"] = relationship("DocumentChunk", backref="kcards")

    def __repr__(self) -> str:
        return f"<KCard id={self.id} chunk={self.chunk_id} title={self.title[:30]}>"


class DocumentParseRecord(Base):
    """Tracks async parse state so we don't re-queue in-flight jobs."""

    __tablename__ = "document_parse_records"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)
    knowledge_item_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("knowledge_items.id", ondelete="CASCADE"),
        unique=True,
        nullable=False,
        index=True,
    )
    # See knowledge.py file_type — same values_callable fix. `parsestatus`
    # Postgres enum was created with lowercase values in 0002.
    status: Mapped[ParseStatus] = mapped_column(
        Enum(ParseStatus, values_callable=lambda obj: [e.value for e in obj]),
        default=ParseStatus.PENDING,
        nullable=False,
    )
    task_id: Mapped[str | None] = mapped_column(String(100), nullable=True)
    error: Mapped[str | None] = mapped_column(Text, nullable=True)
    # Extracted metadata (title, author, page_count, content-type, etc.)
    # Stored as JSON-serialized text to avoid jsonb dialect coupling here.
    metadata_json: Mapped[str | None] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
