app = "ekm-collab"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "1234"
  EKM_BACKEND_URL = "https://ekm-backend.fly.dev"
  EKM_BACKEND_INTERNAL_URL = "http://ekm-backend.internal:8001"

[[services]]
  protocol = "tcp"
  internal_port = 1234

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    type = "connections"
    hard_limit = 200
    soft_limit = 150

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"

[[restart]]
  policy = "always"
